"""empty message

Revision ID: 9165b3b23655
Revises: 
Create Date: 2019-11-04 20:05:15.592339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9165b3b23655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('date', sa.Date(), nullable=True))
    op.alter_column('skus', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('skus', 'order_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('order_date', sa.DATE(), server_default=sa.text("('now'::text)::date"), autoincrement=False, nullable=False))
    op.alter_column('skus', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('skus', 'date')
    # ### end Alembic commands ###
